/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package udea.aldo.war_of_galaxies.view;

/**
 *
 * @author ASUS
 */
public class QuestionsForm extends javax.swing.JFrame {

    /**
     * Creates new form QuestionsForm
     */
    public QuestionsForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qt1Label = new javax.swing.JLabel();
        answ1 = new javax.swing.JComboBox<>();
        qt2Label = new javax.swing.JLabel();
        answ2 = new javax.swing.JComboBox<>();
        qt3Label = new javax.swing.JLabel();
        answ3 = new javax.swing.JComboBox<>();
        qt4Label = new javax.swing.JLabel();
        answ4 = new javax.swing.JComboBox<>();
        qt5label = new javax.swing.JLabel();
        answ5 = new javax.swing.JComboBox<>();
        qt6label = new javax.swing.JLabel();
        answ6 = new javax.swing.JComboBox<>();
        qt7Label = new javax.swing.JLabel();
        answ7 = new javax.swing.JComboBox<>();
        qt8Label = new javax.swing.JLabel();
        answ8 = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        qt1Label.setText("¿Alguna vez has mentido para obtener un beneficio personal sin dañar a otros?");
        getContentPane().add(qt1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 430, 40));

        answ1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        getContentPane().add(answ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        qt2Label.setText("¿Has dañado intencionadamente a un animal o a una persona físicamente?");
        getContentPane().add(qt2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 410, 28));

        answ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        getContentPane().add(answ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        qt3Label.setText("¿Has difundido rumores falsos sobre alguien con el propósito de dañar su reputación?");
        getContentPane().add(qt3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 470, 34));

        answ3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        answ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ3ActionPerformed(evt);
            }
        });
        getContentPane().add(answ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        qt4Label.setText("¿Has robado algo de valor considerable de alguien o un lugar?");
        getContentPane().add(qt4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 370, 40));

        answ4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        getContentPane().add(answ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        qt5label.setText("¿Has hecho daño a alguien emocionalmente a propósito?");
        getContentPane().add(qt5label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 340, 40));

        answ5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        getContentPane().add(answ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        qt6label.setText("¿Has dejado de ayudar a alguien en una situación de emergencia cuando tenías la capacidad de hacerlo?");
        getContentPane().add(qt6label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 570, 40));

        answ6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        getContentPane().add(answ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, -1, -1));

        qt7Label.setText("¿Has disfrutado del sufrimiento de otros?");
        getContentPane().add(qt7Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 230, 40));

        answ7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        getContentPane().add(answ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        qt8Label.setText("¿Has cometido algún delito grave (por ejemplo, asalto, fraude)?");
        getContentPane().add(qt8Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 370, 40));

        answ8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        getContentPane().add(answ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        backButton.setText("←");
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 443, 100, 40));

        jLabel1.setText("Responde las siguientes preguntas:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ3ActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        Powers powersForm = new Powers();
        powersForm.setVisible(true);
        WindowsManager.addWindow(powersForm);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        WindowsManager.closeCurrentAndShowPrevious();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> answ1;
    private javax.swing.JComboBox<String> answ2;
    private javax.swing.JComboBox<String> answ3;
    private javax.swing.JComboBox<String> answ4;
    private javax.swing.JComboBox<String> answ5;
    private javax.swing.JComboBox<String> answ6;
    private javax.swing.JComboBox<String> answ7;
    private javax.swing.JComboBox<String> answ8;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel qt1Label;
    private javax.swing.JLabel qt2Label;
    private javax.swing.JLabel qt3Label;
    private javax.swing.JLabel qt4Label;
    private javax.swing.JLabel qt5label;
    private javax.swing.JLabel qt6label;
    private javax.swing.JLabel qt7Label;
    private javax.swing.JLabel qt8Label;
    // End of variables declaration//GEN-END:variables
}
